package com.sample;

import com.sample.*;
import java.util.Date;
import com.sample.Cliente;

//Procedencia de Proyectos
rule "Project Country"
	salience 10
when
	proyecto: Proyecto(); 
	stranger: boolean() from proyecto.isPais_ue();
then
	proyecto.setAceptado(true);
end

//Caducidad del Cliente

rule "Client Dead"
	salience 20
when
	cliente: Cliente()
	plazo: Boolean() from cliente.calculatsa();
then
	cliente.setPlazovencido(true);
end

//Cierre de Proyectos



